import { StyleSheet } from 'react-native';

export const getNotificationStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  bellContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 99,
  },
  bellButton: {
    padding: 8,
    backgroundColor: 'transparent',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: 'red',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  badgeText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
    textAlign: 'center',
  },
  notificationDropdown: {
    position: 'absolute',
    top: 50,
    right: 8,
    width: 320,
    backgroundColor: theme === 'dark' ? '#23272F' : '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme === 'dark' ? '#444' : '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
    zIndex: 200,
    maxHeight: 400,
  },
  dropdownHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme === 'dark' ? '#333' : '#eee',
  },
  notificationsContainer: {
    maxHeight: 350,
  },
  scrollContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  scrollViewContent: {
    paddingBottom: 16,
  },
  emptyNotificationText: {
    color: theme === 'dark' ? '#888' : '#666',
    textAlign: 'center',
    paddingVertical: 20,
  },
  notificationItem: {
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderBottomColor: theme === 'dark' ? '#333' : '#eee',
    borderBottomWidth: 1,
  },
  notificationTitle: {
    fontWeight: 'bold',
    color: theme === 'dark' ? '#e0e0e0' : '#222',
    flexWrap: 'wrap',
    width: '100%',
  },
  notificationBody: {
    color: theme === 'dark' ? '#cccccc' : '#444',
    marginTop: 4,
    flexWrap: 'wrap',
    width: '100%',
    lineHeight: 18,
  },
  notificationTimestamp: {
    fontSize: 11,
    color: '#888',
    marginTop: 2,
    textAlign: 'right',
  },
  markAllAsRead: {
    marginTop: 6,
    alignSelf: 'flex-end',
    padding: 6,
    backgroundColor: '#e67e22',
    borderRadius: 6,
  },
  markAllText: {
    color: '#f0f0f0',
    fontWeight: 'bold',
    fontSize: 13,
  },
  clearAllButton: {
    marginLeft: 8,
    padding: 6,
    backgroundColor: '#d32f2f',
    borderRadius: 6,
    alignSelf: 'flex-end',
  },
  clearAllText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
  },
});

